name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go:
        - '1.14'
        - '1.15'
        - '1.16'
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make test
